language: scala

sudo: true

dist: xenial

scala:
   - 2.11.12
   - 2.12.10
   
jdk:
  - openjdk8

sbt_args: -J-Xmx8192M

install:
  - pip install --user codecov
  
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier

script:
  sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport